export const GET_ADMIN = "GET_ADMIN";
export const DETAIL_USER_SUCCESS = "DETAIL_USER_SUCCESS";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
