export const TOPUPADM = "TOPUPADM";
export const EDIT_TOPUP_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_TOPUP_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_TOPUP_FAILED = "EDIT_USER_FAILED";
export const DELETE_TOPUP_REQUEST = "DELETE_TOPUP_REQUEST";
export const DELETE_TOPUP_SUCCESS = "DELETE_TOPUP_SUCCESS";
export const DELETE_TOPUP_FAILED = "DELETE_TOPUP_FAILED";